In [ ]:
import torch

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

In [ ]:
x_2 = inputs[1] #A
d_in = inputs.shape[1] #B
d_out = 2

In [ ]:
torch.manual_seed(123)
#Basically (d_in,d_out) = (3,2)
W_query = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_key = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)

In [ ]:
print(W_query)

Parameter containing:
tensor([[0.2961, 0.5166],
        [0.2517, 0.6886],
        [0.0740, 0.8665]])


In [ ]:
print(W_key)

Parameter containing:
tensor([[0.1366, 0.1025],
        [0.1841, 0.7264],
        [0.3153, 0.6871]])


In [ ]:
print(W_value)

Parameter containing:
tensor([[0.0756, 0.1966],
        [0.3164, 0.4017],
        [0.1186, 0.8274]])


In [ ]:
#This is just for the example
#Journey ke liye
query_2 = x_2 @ W_query 
key_2 = x_2 @ W_key
value_2 = x_2 @ W_value
print(query_2)#This is the exact answer which i have written in the Notes

tensor([0.4306, 1.4551])


In [ ]:
#This is the main calculation
key = inputs @ W_key
value = inputs @ W_value
query = inputs @ W_query
#This easily depicts the dimensions of the Key, Queries, Values
print(key)
print("Shape of the Key: ",key.shape)
print(value)
print("Shape of the Value: ",value.shape)
print(query)
print("Shape of the Query",query.shape)

tensor([[0.3669, 0.7646],
        [0.4433, 1.1419],
        [0.4361, 1.1156],
        [0.2408, 0.6706],
        [0.1827, 0.3292],
        [0.3275, 0.9642]])
Shape of the Key:  torch.Size([6, 2])
tensor([[0.1855, 0.8812],
        [0.3951, 1.0037],
        [0.3879, 0.9831],
        [0.2393, 0.5493],
        [0.1492, 0.3346],
        [0.3221, 0.7863]])
Shape of the Value:  torch.Size([6, 2])
tensor([[0.2309, 1.0966],
        [0.4306, 1.4551],
        [0.4300, 1.4343],
        [0.2355, 0.7990],
        [0.2983, 0.6565],
        [0.2568, 1.0533]])
Shape of the Query torch.Size([6, 2])


In [ ]:
keys_2 = key[1]
attn_score_22 = query_2.dot(keys_2)

In [ ]:
attn_scores_2 = query_2 @ key.T
print(attn_scores_2)

tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])


In [ ]:
attn_scores = query @key.T
print(attn_scores)

tensor([[0.9231, 1.3545, 1.3241, 0.7910, 0.4032, 1.1330],
        [1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440],
        [1.2544, 1.8284, 1.7877, 1.0654, 0.5508, 1.5238],
        [0.6973, 1.0167, 0.9941, 0.5925, 0.3061, 0.8475],
        [0.6114, 0.8819, 0.8626, 0.5121, 0.2707, 0.7307],
        [0.8995, 1.3165, 1.2871, 0.7682, 0.3937, 1.0996]])


In [ ]:
d_k = key.shape[-1]
attn_weights_2 = torch.softmax(attn_scores_2 / d_k**2, dim=-1)
print(attn_weights_2)
print(d_k)

tensor([0.1623, 0.1877, 0.1858, 0.1547, 0.1358, 0.1738])
2


In [ ]:
import torch
tensor = torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])
softmax_result = torch.softmax(tensor, dim = -1)
print("Softmax without scaling:", softmax_result)

#Multiplying krdo by 8
scaled_tensor = tensor * 8
softmax_scaled_result = torch.softmax(scaled_tensor, dim = -1)
print("Softmax after scaling(tensor * 8)",softmax_scaled_result)

Softmax without scaling: tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])
Softmax after scaling(tensor * 8) tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])


In [ ]:
import numpy as np

# Function to create variance before and after scaling
def compute_var(dim, num_trials=1000):
    dot_products = []
    scaled_dot_products = []

    for _ in range(num_trials):
        q = np.random.randn(dim)
        k = np.random.randn(dim)

        dot_prod = np.dot(q, k)
        dot_products.append(dot_prod)

        # scale the dot product by sqrt(dim)
        scaled_dot_prod = dot_prod / np.sqrt(dim)
        scaled_dot_products.append(scaled_dot_prod)

    var_before_scaling = np.var(dot_products)
    var_after_scaling = np.var(scaled_dot_products) 

    return var_before_scaling, var_after_scaling

var_before_5, var_after_5 = compute_var(5)
print(f"Variance before scaling (dim=5): {var_before_5:.4f}")
print(f"Variance after scaling  (dim=5): {var_after_5:.4f}")

var_before_20, var_after_20 = compute_var(20)
print(f"Variance before scaling (dim=100): {var_before_20:.4f}")
print(f"Variance after scaling  (dim=20): {var_after_20:.4f}")


Variance before scaling (dim=5): 4.7285
Variance after scaling  (dim=5): 0.9457
Variance before scaling (dim=100): 19.9320
Variance after scaling  (dim=20): 0.9966


In [ ]:
import numpy as np

# Function to create variance before and after scaling
def compute_var(dim, num_trials=1000):
    dot_products = []
    scaled_dot_products = []

    for _ in range(num_trials):
        q = np.random.randn(dim)
        k = np.random.randn(dim)

        dot_prod = np.dot(q, k)
        dot_products.append(dot_prod)

        # scale the dot product by sqrt(dim)
        scaled_dot_prod = dot_prod / np.sqrt(dim)
        scaled_dot_products.append(scaled_dot_prod)

    var_before_scaling = np.var(dot_products)
    var_after_scaling = np.var(scaled_dot_products) 

    return var_before_scaling, var_after_scaling

var_before_5, var_after_5 = compute_var(5)
print(f"Variance before scaling (dim=5): {var_before_5:.4f}")
print(f"Variance after scaling  (dim=5): {var_after_5:.4f}")

var_before_100, var_after_100 = compute_var(100)
print(f"Variance before scaling (dim=100): {var_before_100:.4f}")
print(f"Variance after scaling  (dim=20): {var_after_100:.4f}")


Variance before scaling (dim=5): 4.8975
Variance after scaling  (dim=5): 0.9795
Variance before scaling (dim=100): 97.1490
Variance after scaling  (dim=20): 0.9715


In [ ]:
 #If we dont use square root the variance will not be close to 1

In [ ]:
#Ab hoga Context vector calculate
#Journey ka context vector
context_vec_2 = attn_weights_2 @ value
print(context_vec_2)

tensor([0.2896, 0.7811])


In [ ]:
#Implementing a Compact Self Attention
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self,d_in,d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in,d_out))
        self.W_key = nn.Parameter(torch.rand(d_in,d_out))
        self.W_value = nn.Parameter(torch.rand(d_in,d_out))
        
    def forward(self,x):
        keys = x@self.W_key
        queries = x@self.W_query
        values = x@self.W_value

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1] ** 0.5, dim = -1

        )
        context_vec = attn_weights @ values
        return context_vec


In [ ]:
import torch
#Creting an instance of class
torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in,d_out)
print(sa_v1(inputs))

tensor([[0.2996, 0.8053],
        [0.3061, 0.8210],
        [0.3058, 0.8203],
        [0.2948, 0.7939],
        [0.2927, 0.7891],
        [0.2990, 0.8040]], grad_fn=<MmBackward0>)


In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

class SelfAttention_v2(nn.Module):
    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        queries = self.W_query(x)   
        keys    = self.W_key(x)     
        values  = self.W_value(x)   

        attn_scores = torch.matmul(queries, keys.transpose(-2, -1))  
        attn_scores = attn_scores / (keys.shape[-1] ** 0.5)  
        attn_weights = F.softmax(attn_scores, dim=-1)

        # Weighted sum of values
        context_vec = torch.matmul(attn_weights, values)  # (batch, seq_len, d_out)
        return context_vec


In [ ]:
#For more optimised approach we have to apply nn.linear in place of
#nn.parameter

torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in,d_out)
print(sa_v2(inputs))


tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


In [ ]:
queries = sa_v2.W_query(inputs) #A value
keys = sa_v2.W_key(inputs)
attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1] ** 0.5, dim = 1)
print("Ye rha Attention weights: ",attn_weights)



Ye rha Attention weights:  tensor([[0.1921, 0.1646, 0.1652, 0.1550, 0.1721, 0.1510],
        [0.2041, 0.1659, 0.1662, 0.1496, 0.1665, 0.1477],
        [0.2036, 0.1659, 0.1662, 0.1498, 0.1664, 0.1480],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.1661, 0.1564],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.1585],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
#Ex of torch.tril (Lower triangular matrix)
context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length,context_length))
print(mask_simple)

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])


In [ ]:
masked_simple = attn_weights * mask_simple
print(masked_simple)


tensor([[0.1921, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2041, 0.1659, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2036, 0.1659, 0.1662, 0.0000, 0.0000, 0.0000],
        [0.1869, 0.1667, 0.1668, 0.1571, 0.0000, 0.0000],
        [0.1830, 0.1669, 0.1670, 0.1588, 0.1658, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<MulBackward0>)


In [ ]:
#Third step is to normalize as the rows are not becoming equal to one
#Renormalising 

row_sums = masked_simple.sum(dim = 1,keepdim=True)
masked_simple_norm = masked_simple / row_sums
print("Now sum is 1 for the row: \n",masked_simple_norm)

Now sum is 1 for the row: 
 tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<DivBackward0>)


In [ ]:
print(attn_scores)

tensor([[ 0.2899,  0.0716,  0.0760, -0.0138,  0.1344, -0.0511],
        [ 0.4656,  0.1723,  0.1751,  0.0259,  0.1771,  0.0085],
        [ 0.4594,  0.1703,  0.1731,  0.0259,  0.1745,  0.0090],
        [ 0.2642,  0.1024,  0.1036,  0.0186,  0.0973,  0.0122],
        [ 0.2183,  0.0874,  0.0882,  0.0177,  0.0786,  0.0144],
        [ 0.3408,  0.1270,  0.1290,  0.0198,  0.1290,  0.0078]],
       grad_fn=<MmBackward0>)


In [ ]:
# mask = torch.triu(torch.ones(context_length,context_length),diagonal = 1)
# print(mask)

tensor([[0., 1., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0., 0.]])


In [ ]:
mask = torch.triu(torch.ones(context_length,context_length),diagonal = 1)
masked = attn_scores.masked_fill(mask.bool(), -torch.inf)
print(masked) #formula for exponenial

tensor([[0.2899,   -inf,   -inf,   -inf,   -inf,   -inf],
        [0.4656, 0.1723,   -inf,   -inf,   -inf,   -inf],
        [0.4594, 0.1703, 0.1731,   -inf,   -inf,   -inf],
        [0.2642, 0.1024, 0.1036, 0.0186,   -inf,   -inf],
        [0.2183, 0.0874, 0.0882, 0.0177, 0.0786,   -inf],
        [0.3408, 0.1270, 0.1290, 0.0198, 0.1290, 0.0078]],
       grad_fn=<MaskedFillBackward0>)


In [ ]:
attn_weights = torch.softmax(masked / keys.shape[-1] ** 0.5, dim = 1)
print("Ye rha Attention weights: \n",attn_weights)

Ye rha Attention weights: 
 tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5517, 0.4483, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3800, 0.3097, 0.3103, 0.0000, 0.0000, 0.0000],
        [0.2758, 0.2460, 0.2462, 0.2319, 0.0000, 0.0000],
        [0.2175, 0.1983, 0.1984, 0.1888, 0.1971, 0.0000],
        [0.1935, 0.1663, 0.1666, 0.1542, 0.1666, 0.1529]],
       grad_fn=<SoftmaxBackward0>)


In [ ]:
#Ab hogi dropout masking
#We use a dropout rate of 50 percent which means we will dropout the half of attention weights
#Jb gpt models train honge tb lower dropout(0.1 ya 0.2)

torch.manual_seed(123)
dropout = torch.nn.Dropout(0.5)
ex = torch.ones(6,6)
print(dropout(ex))
#After dropout each weights will rescale

In [ ]:
torch.manual_seed(123)
print(dropout(attn_weights))

In [ ]:
#Now we will implement Causal attention class
# We also need to ensure that we are able to handle more than one batches output
#2 inputs with 6 tokens each
# and each token has embedding dim 3

batch = torch.stack((inputs, inputs),dim = 0)
print(batch.shape)

In [ ]:
class CausalAttention(nn.Module):
    def __init__(self, d_in, d_out, context_length,
                 dropout, qkv_bias=False):
        super().__init__()  
        self.d_out = d_out
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.dropout = nn.Dropout(dropout) # New
        context_length = 6
        torch.ones(6,6)
        self.register_buffer('mask', torch.triu(torch.ones(context_length, context_length), diagonal=1)) # New

    def forward(self, x):
        b, num_tokens, d_in = x.shape # New batch dimension b
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.transpose(1, 2) # Changed transpose
        attn_scores.masked_fill_(  # New, _ ops are in-place
            self.mask.bool()[:num_tokens, :num_tokens], -torch.inf)  # `:num_tokens` to account for cases where the number of tokens in the batch is smaller than the supported context_size
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )
        attn_weights = self.dropout(attn_weights) # New

        context_vec = attn_weights @ values
        return context_vec

In [ ]:
torch.manual_seed(123)
context_length = batch.shape[1]
ca = CausalAtttention(d_in,d_out,context_length,0.0)
context_vecs = ca(batch)
print("Context_vecs.shape",context_vecs.shape)

In [ ]:
print(context_vecs)